import { type OxlintConfig, defineConfig } from 'oxlint';

export const typescript: OxlintConfig = defineConfig({
  categories: {
    correctness: 'error',
    nursery: 'error',
    pedantic: 'error',
    perf: 'error',
    restriction: 'error',
    style: 'error',
    suspicious: 'error',
  },
  plugins: ['typescript', 'eslint', 'oxc', 'unicorn', 'import', 'promise'],
  options: {
    typeAware: true,
    typeCheck: true,
    denyWarnings: true,
    reportUnusedDisableDirectives: 'error',
  },
  rules: {
    'capitalized-comments': 'off',
    'id-length': ['error', { exceptionPatterns: ['[A-Z]'], exceptions: ['_', 'i', 't'] }],
    'import/consistent-type-specifier-style': ['error', 'prefer-inline'],
    'import/group-exports': 'off',
    'import/max-dependencies': ['error', { ignoreTypeImports: true, max: 20 }],
    'import/no-named-export': 'off',
    'import/no-relative-parent-imports': 'off',
    'import/no-unassigned-import': ['error', { allow: ['**/*.css'] }],
    'import/prefer-default-export': 'off',
    'no-magic-numbers': ['error', { ignore: [0] }],
    'no-plusplus': ['error', { allowForLoopAfterthoughts: true }],
    'no-ternary': 'off',
    'no-undefined': 'off',
    'no-warning-comments': 'off',
    'max-lines': ['error', { skipBlankLines: true, skipComments: true }],
    'max-lines-per-function': ['error', { skipBlankLines: true, skipComments: true }],
    'max-statements': ['error', { max: 20 }],
    'one-var': 'off',
    'oxc/no-async-await': 'off',
    'oxc/no-rest-spread-properties': 'off',
    'sort-imports': 'off',
    'sort-keys': 'off',
    'typescript/array-type': ['error', { default: 'generic' }],
    'typescript/explicit-function-return-type': 'off',
    'typescript/explicit-module-boundary-types': 'off',
    'typescript/ban-ts-comment': 'off',
    'typescript/consistent-type-imports': ['error', { fixStyle: 'inline-type-imports' }],
    'typescript/no-import-type-side-effects': 'off',
    'typescript/prefer-readonly-parameter-types': 'off',
    'typescript/promise-function-async': 'off',
    'unicorn/filename-case': 'off',
    'unicorn/no-array-for-each': 'off',
  },
});
